$screens = @(
    @{ name = "QR_Scan_Landing_Page"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sX2EzNjRjMGE3MTA2OTRjNDViODUyY2ZiNmU1MmJmNzI2EgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidUDLVg09P9iQC3Y9bolTLkkAj_fIfg_apYMaLr4dgrsvaKp-EvL0EVUq2J3XRFbs0kNXPKnfBRcjirh_qbIFhTT3PeyP5zeJ7jR745CmVGExAQAMF4J2A4vaAn9_95ak7h3KluNqKiwHMH5FbYBDd9bA4Xk7oYpwhYkm0p14uWNlhJmkRgSKOQrYn1mKwOINVGGQEXpJBrYn9b1qPkjkyPLofiNHlBPeqkFEFlj-hraGXxR4g-oNhITFQ" },
    @{ name = "Token_Registration_Welcome"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzIyNmMzY2UzZDY0ODRjNmI5ZGIwMGJhYmIwNzE4ZWU3EgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidU0wP-zSM4LjMwWxD3DZiKeppfpL58raIdsa1g8eOX66rvBFIuiK82WLZGmmmO0KEUfcYrPZ6S9P39dtxRXxd4ZJ1tduEYTshygYm9LZJljp74xEi9XVOMcBaOCny4vtKshZfICJ5V3ArmmL-OI_9Fz5wgyNbAG77tC6nYDfOINIAHny7YTr_OGuwPDYWAjOfuazaTWEDVHvgmFpNanBj-rxmD1WNFEcj9Dptsm4uzZhNiWfO1kXIj42Q" },
    @{ name = "Symptom_Voice_Input"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzQ5NTQ5ODM0MTU4YTRjMDNhMjE4ZDQwNTQ4NWQ3ZmRiEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidWtfjSUy4luq2MfuYRIhyjRF91QPhkZ-XKWqoe04Ly8sStGPZegSnLqmsqq4aHTd_bjWIWEls0seCTWj6d08LPI-XVIQymW-CYhP3cAM5j9DrfGUDcDmMbOXQuVzU4BzMJ-Xxln1Wuh9NMIpvfbOq7JaWgwmeIS89XmFS9gMjM9_lPulC-7pohpDdvIcxbt9uaz5p1l6NMUXlIs3_AAXblFC4LrCn0HRatUU71YvikymEBtwT2r2k_VYQ" },
    @{ name = "Your_Health_Brief"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzVhMzQ0ZmJiZTg5MTRjZWE4YzIwZDViZmZiNDkxZjFlEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidVDkrQxuwHrxyTpf2YpDam43vC7oSIj2gB_JNvD82insbI-Io-MgjjvkE4PHm52BxJ8hIa3B6djh0NhcwoPWY6gjLj0O30Cc6ffM8iEeQtUj1VIlN5VQwAA2VeyayNa5GXwzwsrQ9v3vKD4H4XNfA5LatmMkUZrsg68AclK1-t3rMvXp8_YdQnuR3vvrSoLd4iuYjG9uGeq--RQLH1s4wcIiNLolgo2lO43zACzwq3L69USLsjz0d1u" },
    @{ name = "Your_Turn_Alert"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzJlNWYyY2U1Y2M0NDRjMDdhYjI2ZjMxYWE2MTcxNTNlEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidWor1Oh1zEIn7H4Rn9P_fueH-PamMwrEJxMvgIQNyu63LAWvBz8nS9us_sYrIATQNtstG3OHvhCOH4HrCClBzztANhFbSgzfRBMXFEeT6sPi3yEMqWu5rnG99F1cZ-iaZEE_2XLGN7QlSX-_8txTT4IbHUvhsYrYmPvRf3-ISL7oJ3WSbPBwwJMbX0x-t_Kagwg1H27uq_DQN7nRENI8smnA_BUPYnByDF_3VPUpf9TyC50vAJW-dUT" },
    @{ name = "Post_Visit_Screen"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzBjMmQ0NjE3ZjVkYjRhMzA4MzBlNzFkMzYyYzk0ZDQyEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidWLpxhGSLPNbiezzydac9g1Edx-XE5PtpJMmX5DS_zD-FyS61q47c1gqztTxFQrNF1mmxxlnPvfo9b3tkNHPE4MHcuq5seEqhkmUewmuMA12z9s9Asls-TEVDVgnX6PxwkKVzqH-3wWq_Zxpu2zG9Afi9VrXjTvfHxVhcnXzZyVkpeKpOAvDcDbMWdf1x6X2eHwdcFJqfBsXI7cxZY1tPo8du0vdRaKR_YXd3tdNxQ86X554rVBrk5Qhg" },
    @{ name = "Main_Dashboard"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzAzZjRkMDYzMmQxOTQ5YTNhOTk0YmVlYmRmZDJiODU3EgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidViVV7Ujv8q6As9bt4ixtz-0HLH4nvbpCuzoFTaaWFPfqn7BP4HpURdrNLyV1cM-rtasouLXmBHP9wjFMxAVXdDrFraY7yKrhEfDHBZ82Emss7KBziZ7vHbCiaQ0kAgX_Kpn0Wb3H0qVYYfDCq1LyRaF6RRxAN4GcrjZAZYRu7Qe9z6Cdb5_AKUYkYG97DzXuGQlnWpwnxscSmlYF1Vwgi7bteumGoXxK46O53Sf-LFzBhaBf58spKmNw" },
    @{ name = "Patient_Symptom_Summaries"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzhhODM4OGQ4ZTZlNTQyOWJhNmJkYTExY2I3N2M2OTM0EgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidVJH-fP1hWe-ysUWnfU_lvd3k_Bxa3MQyikeuSzPsoTKJp5XllADP1YcESYgzQe7Tz6nPy9TO8qJkskDfVWruB_V70s_qtnVUedcCrGvri5wH8d0-nayPYbBZ5pc9_ispd4RsU3Wv9Rlfpowsa6pSkA785Kv3ynM6wVTUSl6hTgu13-2ktrrD-d4Qwi1ccdUykIqfsMx8XY-Sy_juQImgvfO_nM1X-6A7hL57sNkKWE0UA4YZzpPGMiyg" },
    @{ name = "Analytics_Page"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzhlMTg3NjVhYWY3NzQ3MDViZDA1ZTNlNTlmNGEzNmZlEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidXTNfh4ODb4yDASjHM8TOgaII2dY2tR0jvap0jNtZSDe_VagVF7tUND4Fj_dfbwNxX35OCZUFoQ1FNUcMt4ziyrsyvTy8Oyia1lmdYx95sqMZPr5InoYrcnJcrrtD3x5xI5_z5kBn4wDxZiQTB_R66PkAxvhgHFqAOOfDqrN5931PWXJIP0KFOPpoIytznWxFKz2aSeRHobGp5pJ0g8OD4Lepdpi1f-dpDgpZVr_I_UCgyi7lxKaJQFTg" },
    @{ name = "WhatsApp_Integration"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzhkNTI1NWEzZjFmNjRiOWM4Y2NhOTk3ZDQ1M2I3MGYzEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidVjfZD8kBCrcjSu90rKbcNko0_NUvcDgdESkNfzZaeblA1Chp3PthJRkv35qQKff3qfq2AyiUyXBUG0csi49L5_qJqdXWkZcCJEslat0Acgt2zdOmfqqpnI3dA_08Ke1t_wLNWlxRHusUqD8l6j4vG8wND6iX8T8z9YjuEcy3eWPZrYgyZXuECWO99NxcqG0d8BbWfV01i_S9EN2yjnDHdu-esxzx_AloeIm4IdT7zOBjohi4PhYRbl" },
    @{ name = "Emergency_Alert_Panel"; html = "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ6Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpZCiVodG1sXzJhOGEwMDc3MzQ3NzRkNGQ5MzZhNTcyZmM5NzMxYjBkEgsSBxCKmOLymQgYAZIBIgoKcHJvamVjdF9pZBIUQhI0OTEyMzk2MTgzNTI4MTU3OTk&filename=&opi=89354086"; image = "https://lh3.googleusercontent.com/aida/AOfcidXzQM4g71fnTEJqLnb6kh5ui5NQzYm2P8X_crWQ3fbnLUiw8V2WG38Shw1Jlm7Jb9kCT7vm9CQK9gfrjLGFLe4yXx_lIFJRbOtoQyKfgYV_vGIBNNWTpzUOtBaZJtM78HaelVxKrLXTXD3gQGWq8pd46qQZXx1bbLJFOpmyTDqRnxEeigqSPzeYkfRYmR6punupCF7CxG0q8V-kil5zQd0MFs_gC0aI_Vc0ywbkkAn5GgDM1cfy5K53AQ" }
)

$targetDir = "c:\Users\abdul\.gemini\antigravity\scratch\Queue iq\Stitch_Screens"
New-Item -ItemType Directory -Force -Path $targetDir | Out-Null

foreach ($screen in $screens) {
    Write-Host "Downloading $($screen.name)..."
    $htmlPath = Join-Path $targetDir ($screen.name + ".html")
    $imagePath = Join-Path $targetDir ($screen.name + ".webp")
    
    curl.exe -s -L $screen.html -o $htmlPath
    curl.exe -s -L $screen.image -o $imagePath
}
Write-Host "All downloads complete."
